name: Flask Webapp CI/CD Pipeline with KinD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
    - name: Checkout code repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
    - name: Build and Push to Docker Hub
      run: |
        docker build -t webapp-flask .
        docker tag webapp-flask:latest devchukwudi/webapp-flask
        docker push devchukwudi/webapp-flask:latest


  test:
    
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Test stage
      run: echo "This is the testing stage" 


  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure deploy runs after the build

    steps:
    - name: Checkout code repository
      uses: actions/checkout@v4
    # Step 1: Set up KinD cluster
    - name: Set up KinD cluster
      uses: helm/kind-action@v1.2.0

    # Step 2: Apply Kubernetes manifests
    - name: Deploy to KinD Kubernetes 
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    - name: Verify Deployment
      run: kubectl get pods


